/* おみくじの運勢の文(あらかじめ用意した文。番号ごとに組み合わせが決まる)
   [大吉, 中吉, 小吉, 凶] × 8項目 × 4通り */
export const CATS = { ja: ["願望", "待人", "失物", "旅行", "仕事", "学問", "恋愛", "金運"], en: ["Wish", "Visitor", "Lost item", "Travel", "Work", "Study", "Love", "Money"] };
export const FORTUNE = {
  ja: [
    [["思うままに叶う", "速やかに叶う　迷うな", "願い通りになる", "人の助けありて叶う"], ["来る　喜びあり", "音信あり　早く来る", "思わぬ人来たる", "来る　連れあり"], ["出る　高き所を探せ", "すぐに見つかる", "東の方にあり　出る", "人に聞けば出る"], ["どこへ行くも吉", "南の方よし　実りあり", "思い立つ日が吉日", "連れと行け　楽しみ多し"], ["利益あり　手を広げよ", "思い切って進めて吉", "人の縁より福来る", "大いに栄える"], ["努力が実る", "安心して励め", "望み通りの成果あり", "師の言葉を大切に"], ["想いは必ず通じる", "真心を伝えよ　結ばれる", "良き縁に恵まれる", "ためらわず進め"], ["財を得る　施せばなお良し", "思わぬ実入りあり", "蓄えれば大いに増す", "使うほど巡り来る"]],
    [["少し遅れて叶う", "焦らねば叶う", "努めれば叶う", "人に頼れば叶う"], ["遅れて来る", "たよりあり", "来るが時かかる", "待てば来る"], ["出る　身近な所", "時が経てば出る", "出る　低き所", "家の内にあり"], ["近くならば吉", "支度を整えれば吉", "急がず行け", "西の方よし"], ["地道に続ければ利あり", "堅実にせよ", "小さく始めて吉", "時を待て　好機来る"], ["努力次第で伸びる", "基礎を固めよ", "焦らず進め", "繰り返し学べ"], ["誠意を見せよ", "ゆっくり育てよ", "言葉を惜しむな", "相手の話をよく聞け"], ["無駄を省けば増す", "ほどほどにあり", "堅く守れば吉", "少しずつ貯まる"]],
    [["時を待て", "叶うが遅し", "一歩ずつ進め", "欲張らねば叶う"], ["来るが遅い", "音信は遅し", "思わぬ時に来る", "たよりのみあり"], ["探せば出る　遅し", "出るが手間取る", "人に尋ねよ", "物の下にあり"], ["近場なら吉", "無理をするな", "支度を念入りに", "日を改めよ"], ["利は少なし　続けよ", "慎重に進めよ", "人と争うな", "今は準備の時"], ["油断するな", "苦手を克服せよ", "基本に立ち返れ", "少しずつ伸びる"], ["焦るな　時を待て", "気持ちを素直に", "友から始めよ", "無理に押すな"], ["出費に注意", "浪費をつつしめ", "小さな得あり", "貯めることを覚えよ"]],
    [["今は叶い難し　時を待て", "望みを小さくせよ", "焦れば遠のく", "心を改めれば道開く"], ["来ず", "来るが遅し", "たよりなし", "あきらめず待て"], ["出難し", "出るが遅し", "諦めずに探せ", "思わぬ所にあり"], ["見合わせよ", "近場に留めよ", "急ぐべからず", "慎重にせよ"], ["損あり　控えよ", "今は動くな", "人の言葉に惑うな", "守りを固めよ"], ["油断大敵", "基本からやり直せ", "怠れば落ちる", "努力を惜しむな"], ["今は控えよ", "言葉に気をつけよ", "焦らず待て", "誤解を解け"], ["出費多し　つつしめ", "貸し借りするな", "無駄遣いに注意", "今は守れ"]]],
  en: [
    [["Granted as you wish", "Granted soon; don't hesitate", "It will go your way", "Granted with help from others"], ["Comes, bringing joy", "News soon; they come early", "Someone unexpected arrives", "Comes with company"], ["Found; look up high", "Found right away", "Found toward the east", "Ask around and it turns up"], ["Good wherever you go", "Go south; it pays off", "The day you decide is lucky", "Go with a friend; much fun"], ["Profit; expand boldly", "Push forward; it goes well", "Luck comes through people", "Great prosperity"], ["Effort pays off", "Study with confidence", "The results you hoped for", "Treasure your teacher's words"], ["Your feelings will reach them", "Speak from the heart; you'll be together", "A good match is coming", "Go ahead without hesitating"], ["Wealth comes; share it", "An unexpected gain", "Save and it grows", "What you spend comes back"]],
    [["Granted, a little late", "Granted if you don't rush", "Granted with effort", "Granted if you ask for help"], ["Arrives late", "News will come", "Comes, but it takes time", "Wait and they come"], ["Found close by", "Turns up in time", "Found somewhere low", "It is inside the house"], ["Good if nearby", "Good if well prepared", "Travel without hurry", "Go west"], ["Steady work brings profit", "Play it safe", "Start small", "Wait; a chance will come"], ["You grow with effort", "Build the basics", "Don't rush", "Review again and again"], ["Show sincerity", "Let it grow slowly", "Don't hold back your words", "Listen closely to them"], ["Cut waste and it grows", "Enough, not more", "Guard it well", "It builds up slowly"]],
    [["Wait for the right time", "Granted, but late", "One step at a time", "Granted if you don't ask too much"], ["Comes late", "News is slow", "Comes when you least expect", "Only a letter comes"], ["Found late if you search", "Found, with some trouble", "Ask someone", "It is under something"], ["Good if close by", "Don't push yourself", "Prepare carefully", "Pick another day"], ["Small profit; keep going", "Proceed with care", "Avoid quarrels", "Now is time to prepare"], ["Don't get careless", "Work on your weak spots", "Go back to the basics", "Slow but steady growth"], ["Don't rush; wait", "Be honest about your feelings", "Start as friends", "Don't push too hard"], ["Watch your spending", "Avoid waste", "A small gain", "Learn to save"]],
    [["Hard for now; wait", "Wish for less", "Rushing pushes it away", "Change your heart and a way opens"], ["Does not come", "Comes late", "No news", "Keep waiting"], ["Hard to find", "Found late", "Keep searching", "In an unexpected place"], ["Put it off", "Stay close to home", "Do not hurry", "Be careful"], ["Loss; hold back", "Don't move now", "Don't be swayed by talk", "Strengthen your defenses"], ["Carelessness is your enemy", "Start again from the basics", "Slack off and you fall behind", "Spare no effort"], ["Hold back for now", "Mind your words", "Wait patiently", "Clear up misunderstandings"], ["Heavy spending; be careful", "Don't lend or borrow", "Beware of waste", "Protect what you have"]]] };
